server:
  port: 8083

spring:
  application:
    name: "bank-microservice"
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: "org.hibernate.dialect.H2Dialect"
#    show-sql: true
  datasource:
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alinedb 
  jackson:
    serialization:
      INDENT_OUTPUT: true

app:
  sms:
    enable: false
  email:
    enable: false
  security:
    secret-key: "ThisIsAGreatSecretKey!!!"
    jwt:
      secret-key: "21b4054a-1c75-4e8a-aacd-93aaaad92e19"
