server:
  port: 8071

spring:
  application:
    name: "underwriter-microservice"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alinedb
    initialization-mode: always # This is to automatically insert data.sql

app:
  email:
    enable: true
    from: "no-reply@alinefinancial.com"
  landing-portal: "${PORTAL_LANDING}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  security:
    secret-key: "ThisIsAGreatSecretKey!!!"
    jwt:
      secret-key: "21b4054a-1c75-4e8a-aacd-93aaaad92e19"
  aws:
    email:
      template-bucket-name: s3://jh-alinefinancial-email-templates/
    credentials:
      access-key-id: AKIATRKPORPJQVZACE55
      secret-access-key: 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