server:
  port: 8070

spring:
  application:
    name: "user-microservice"
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alinedb
  jackson:
    serialization:
      INDENT_OUTPUT: true

app:
  sms:
    enable: true
  email:
    from: "no-reply@alinefinancial.com"
    enable: true
  security:
    secret-key: "ThisIsAGreatSecretKey!!!"
    jwt:
      secret-key: "21b4054a-1c75-4e8a-aacd-93aaaad92e19"
  member-dashboard: "http://localhost:4200"
  landing-portal: "http://localhost:3007"
